### ISSUE TITLE
Dashboard cannot be accessed

### ISSUE THREAD

**Issue by cheld** [FujitsuEnablingSoftwareTechnologyGmbH/kubernetes#7]
If a user wants to access Dashboard with

https://<master-ip>/ui

a browser pop-up asks for username and password. However, I could not log in.

User name and password are configured in the file basic_auth.csv. The file is specified for api-server correctly. The contents of the file seems wrong.

The content is:
user,password,admin

On vagrant, the content is:
vagrant, vagrant, admin

See also:
https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/kubernetes/blob/openstack-provider/cluster/openstack/kubernetes-heat/fragments/deploy-kube-auth-files-master.yaml

**Comment by cheld** [comment]
CC @ohtake , @batikanu , @zreigz 

not so high priority. possible workaround is to allow http. (docker based provisioning has higher priority)

**Comment by elsonrodriguez** [comment]
@ohtake , @batikanu , @zreigz, @cheld 

I corrected the order of the file in https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/kubernetes/pull/9/commits/83a180aba5f714388fba6c3465806b8a840e9ea7

However it is still missing proper credentials.

There are some functions in common.sh that can be used to generate information for basic_auth along with the KUBE_BEARER_TOKEN. See the aws provider for example.

I highly recommend that this is done ASAP after this batch of PRs is merged into Kubernetes.
